### ISSUE TITLE
Implementation of Amazon Cognito

### ISSUE THREAD

**Issue by kniec** [XenitAB/go-oidc-middleware#12]
Is there a way to use this middleware with [Amazon Cognito](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-oidc-idp.html)?

**Comment by simongottschlag** [comment]
Hi @kniec! 😊

I haven't used Cognito myself, but my best guess is that it does. I haven't created an example for it, but will keep this issue open and take a look at it when I have some free time!

If you test it yourself, feel free to either paste details here or create a PR.

**Comment by simongottschlag** [comment]
@kniec I've added an Amazon Cognito example. :+1: 

I haven't used it before and wasn't able to get PKCE to work, most likely me missing some kind of config but was able to get it to work by passing the `client_secret` to the token endpoint.

I'm closing this issue for now, but feel free to re-open / open a new one if there are any other question/issues.

**Comment by kniec** [comment]
Cool, thanks a lot. I'll give it a go(lang) in my projects.
