### ISSUE TITLE
support oidc providers authelia and casdoor

### ISSUE THREAD

**Issue by c-nv-s** [XenitAB/go-oidc-middleware#132]
I didn't want to create two separate tickets so I will just outline them here:

https://github.com/authelia/authelia
https://github.com/casdoor/casdoor

both are self-hosted oidc providers. It would be nice if you could add support for either or both of them.

**Comment by simongottschlag** [comment]
Hi @c-nv-s! 😊

Thank you for creating this issue!

This middleware should work with most OpenID Providers out-of-the-box. Have you tried it and seen any specific issues?

We are using it with both node-openid-provider and Ory Hydra, but I haven't tested all providers out there. 😉

The providers listed in the readme and examples is just common SaaS providers that I've validated myself but not in any way limited to them.

**Comment by c-nv-s** [comment]
ah ok perfect, I assumed it was limited to those ones. I'll give it a shot with the two I suggested. feel free to close the ticket.
