### ISSUE TITLE
Default 5 seconds timeout is not enough to load openid-configuration in a slow network environment

### ISSUE THREAD

**Issue by huangyingting** [XenitAB/go-oidc-middleware#148]
Default 5 seconds timeout is not enough to load openid-configuration in a slow network environment, would appreciate if add a configuration parameter to adjust the timeout

panic: oidc discovery: unable to load jwks: unable to fetch jwksUri from discoveryUri (https://login.microsoftonline.com/<Tenant>/v2.0/.well-known/openid-configuration): Get "https://login.microsoftonline.com/<Tenant>/v2.0/.well-known/openid-configuration": context deadline exceeded

goroutine 1 [running]:
github.com/xenitab/go-oidc-middleware/oidcgin.New({0xc0005b1ed8, 0x4, 0x4})
	/home/ythuang/go/pkg/mod/github.com/xenitab/go-oidc-middleware/oidcgin@v0.0.24/gin.go:17 +0xd9
main.main()

**Comment by simongottschlag** [comment]
Hi @huangyingting! 😊

You have the setting `WithJwksFetchTimeout()` that configures this: https://github.com/XenitAB/go-oidc-middleware/blob/main/options/options.go

Or, at least that's the idea! If it doesn't work as expected, please keep me updated 👍

Can you give it a try and see if it helps?

By the way, make sure you set the tenant id for your issuer: https://login.microsoftonline.com/{tenant}/v2.0

In the logs you pasted, there's none.

**Comment by simongottschlag** [comment]
But you are also correct in that the fetchTimeout for the discovery is hard coded: `jwksUri, err := getJwksUriFromDiscoveryUri(h.httpClient, h.discoveryUri, 5*time.Second)`

I'll try to add another option for it!

**Comment by simongottschlag** [comment]
Hi @huangyingting!

Sorry for the delay, life got in the way. :^)

I've just created the `v0.0.27` release containing the new `WithDiscoveryFetchTimeout()` which makes this configurable.
