### ISSUE TITLE
use algorithm to get key from keyhandler

### ISSUE THREAD

**Issue by gitu** [XenitAB/go-oidc-middleware#228]
we have a case where we use two equal keys that only differ based on algorithm but have the same kid in jwk

according to rfc7517
https://www.rfc-editor.org/rfc/rfc7517#section-4.5 

so getting the key as in:
https://github.com/XenitAB/go-oidc-middleware/blob/cd90da12c6aca0ebb0fcf06fc7bd502ee4ef81aa/internal/oidc/oidc.go#L135

should include the algorithm if multiple keys match by id

**Comment by simongottschlag** [comment]
@gitu this has now been released in `v0.0.39`. Thank you for your contribution! :1st_place_medal:
