### ISSUE TITLE
Improve examples

### ISSUE THREAD

**Issue by idc77** [XenitAB/go-oidc-middleware#230]
I'm usually using my fork of this package with gin but now I'm experimenting with ent and graphql and trying to use this package and net/http.

The examples are spaghetti code at its finest.

Make them examples readable, do not make the reader jump around varioud subdirectories, hiding how it works.
Add an example for keycloak, you know the software you can self-host and not hand over your user data to 3rd parties unlike octa, auth0, conginto and especailly azure.

Jank the core oidc package OUT of internal so people can import it and keep up to date with the changes.

JFC! Unstarred this repo because I'm so annoyed by this.

**Comment by simongottschlag** [comment]
Thank you for the amazing feedback @idc77! I will take it into consideration for future improvements.
